# Azure Portal > Storage Account > Access Key
export CONNECTION_STRING="YOUR CONNECTION STRING"

# Azure Container Registry
## Azure Portal > Container Registry > Access Key
export ACR_USERNAME="AZURE CONTAINER REGISTRY USERNAME"
export ACR_PASSWORD="AZURE CONTAINER REGISTRY PASSWORD"
export ACR_REGISTRY="YOUR AZURE CONTAINER REGISTRY REGISTRY"